name: Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-hacs:
    name: "Validate HACS"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Validate
        uses: "hacs/action@main"
        with:
          category: "theme"
